<?php
/**
 * @var \Mirasvit\Feed\Model\Feed $feed
 */
$feed = $this->getFeed();
?>

<div class="admin__field field field-generation_info no-label">
    <div class="admin__field-control control">
        <div id="generation_info" class="control-value admin__field-value">
            <table class="admin__table-secondary" style="margin-bottom: 15px;">
                <tr>
                    <th><?php echo $block->escapeHtml(__('Feed Access Url')) ?></th>
                    <td><a href="<?php echo $block->escapeUrl($feed->getUrl()) ?>" target="_blank"><?php echo $block->escapeUrl($feed->getUrl()) ?></a></td>
                </tr>
                <?php if ($feed->getGeneratedCnt()): ?>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Count')) ?></th>
                        <td><?= $block->escapeHtml($feed->getGeneratedCnt()) ?></td>
                    </tr>
                <?php endif ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Last Generated')) ?></th>
                    <td>
                        <?php echo $block->escapeHtml($block->formatDate(
                            $feed->getGeneratedAt(),
                            \IntlDateFormatter::MEDIUM,
                            true
                        ));
                        ?>
                    </td>
                </tr>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Generation Time')) ?></th>
                    <td><?php echo $block->escapeHtml(gmdate('H:i:s', $feed->getGeneratedTime())) ?></td>
                </tr>
            </table>
        </div>
    </div>
</div>


