<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<script type="text/javascript">
    require(["jquery"], function($) {
        console.log('init');
        $(".submit-form-button").click(function(e){
            e.preventDefault();
            $('#withdrawal_action').val($(this).attr('name'));
            $('#edit_form').submit();
        });
    });
</script>
