<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<?php
/**
 * @var \Magetrend\Affiliate\Block\Account\Recent\Click $block
 */
?>
<div class="block block-dashboard-orders">
    <?php
    $collection = $block->getCollection();
    $count = count($collection);
    ?>
    <div class="block-title order">
        <strong><?php echo  /* @escapeNotVerified */ $block->getTitle(); ?></strong>
    </div>
    <div class="block-content">
        <?php if ($count > 0) : ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?php echo /* @escapeNotVerified */ $block->getTitle(); ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col title">
                            <?php echo  /* @escapeNotVerified */ __('Title') ?>
                        </th>
                        <th scope="col" class="col desc">
                            <?php echo  /* @escapeNotVerified */ __('Description') ?>
                        </th>
                        <th scope="col" class="col program">
                            <?php echo  /* @escapeNotVerified */ __('Affiliate Program') ?>
                        </th>
                        <th scope="col" class="col code">
                            <?php echo  /* @escapeNotVerified */ __('Coupon Code') ?>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($collection as $record) : ?>
                        <tr>
                            <td data-th="<?php echo  $block->escapeHtml(__('Title')) ?>" class="col title">
                                <?php echo  /* @escapeNotVerified */ $record->getSalesruleName() ?>
                            </td>
                            <td data-th="<?php echo  $block->escapeHtml(__('Description')) ?>" class="col desc">
                                <?php echo  /* @escapeNotVerified */ $record->getSalesruleDescription() ?>
                            </td>
                            <td data-th="<?php echo  $block->escapeHtml(__('Affiliate Program')) ?>"
                                class="col program">
                                <?php echo  /* @escapeNotVerified */ $record->getProgramName() ?>
                            </td>
                            <td data-th="<?php echo  $block->escapeHtml(__('Coupon Code')) ?>" class="col code">
                                <span><?php echo  /* @escapeNotVerified */ $record->getCouponCode() ?></span> 
                                <a href="#" class="mtaf-copy">Copy</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else : ?>
            <div class="message info empty">
                <span><?php echo  /* @escapeNotVerified */ __('There is no assigned any coupons') ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
