<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<?php
/**
 * @var \Magetrend\Affiliate\Block\Account\Info $block
 */
?>
<div class="block block-referral-form">
    <div class="block-title"><strong><?php echo $block->escapeHtml(__('Account info')) ?></strong></div>
    <div class="block-content">
        <div class="box box-affiliate-account-info">
            <strong class="box-title"><span>Referral Code</span></strong>
            <div class="box-content">
                <span><?php echo $block->getAccount()->getReferralCode(); ?></span>
                <a href="#" class="mtaf-copy">Copy</a>
            </div>
        </div>

        <div class="box box-affiliate-account-info">
            <strong class="box-title"><span>Balance</span></strong>
            <div class="box-content">
                <?php echo $block->getAccount()->getFormattedBalance(); ?>
            </div>
        </div>

        <div class="box box-affiliate-account-info">
            <strong class="box-title"><span>Total Payout Amount</span></strong>
            <div class="box-content">
                <?php echo $block->getAccount()->getFormattedPayoutAmount(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "mtafCopy": {}
        }
    }
</script>