<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Email\Items */
?>
<?php
$order = $block->getOrder(); // Get the order object
$helper = $this->helper(\Vdcstore\CustomCheckoutFields\Helper\Data::class);
$values1 = $helper->getCustomFieldValue('title_field_1');
$showCustomField1 = $helper->isCustomFieldVisible1();
$customFieldValue = $order ? $order->getCustomField() : '';
?>

<?php if ($order && $showCustomField1 && !empty($customFieldValue)) : ?>
    <section class="admin__page-section order-additional-information">
        <div class="admin__page-section-title">
            <strong class="title"><?= $escaper->escapeHtml(__('Buyer Order Information')) ?></strong>
        </div>

        <div class="admin__page-section-content order-additional-information-container">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th><?= $escaper->escapeHtml($values1) ?></th>
                            <td><?= $escaper->escapeHtml($customFieldValue) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>

<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= $escaper->escapeHtml(__('Items')) ?>
            </th>
            <th class="item-qty">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </th>
            <th class="item-price">
                <?= $escaper->escapeHtml(__('Price')) ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getParentItem()): ?>
                <tbody>
                <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->isMessagesAllowed('order', $_order, $_order->getStore())
        && $_order->getGiftMessageId()
    ): ?>
        <?php $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
            ->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= $escaper->escapeHtml(__('Gift Message for this Order')) ?></h3>
                        <strong><?= $escaper->escapeHtml(__('From:')) ?></strong>
                        <?= $escaper->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= $escaper->escapeHtml(__('To:')) ?></strong>
                        <?= $escaper->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= $escaper->escapeHtml(__('Message:')) ?></strong>
                        <br /><?= $escaper->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
