<?php
/** @var \Magecomp\Chatgptaicontentpro\Block\Adminhtml\Product\Helper $block */
/** @var \Magento\Framework\Escaper $escaper */
?>

<div data-bind="scope: 'magecomp-ai-product-helper'" class="magecomp-ai-product-helper">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<input type="hidden" id="openai_url" name="openai_url" value="<?php /* @escapeNotVerified */ echo $block->getUrl('chatgptaicontentpro/generate/index')?>">
