<?php $product = $block->getProduct(); ?>
<?php $var = $block->getVarModel(); ?>

<table cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate !important;">

    <tr>
        <td class="block-rounded">
            <table cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td class="info-img">
                        <a href="<?php echo $product->getProductUrl(); ?>">
                            <img class="info-img" src="<?php /* @escapeNotVerified */ echo $block->getImage(258, 210); ?>" alt="img" />
                        </a>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 15px;">
                        <table cellspacing="0" cellpadding="0" width="100%">
                            <tr>
                                <td style="text-align:center; width:155px" colspan="2">
                                    <a href="<?php echo $product->getProductUrl(); ?>"><span class="header-sm"><?php /* @escapeNotVerified */ echo $product->getName(); ?></span></a><br />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 15px;">
                        <!--[if mso]>
                        <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="<?php echo $product->getProductUrl(); ?>" style="height:45px;v-text-anchor:middle;width:155px;" arcsize="15%" strokecolor="#ffffff" <?php echo $var->getHtmlAttribute('fillcolor', 'review_grid_button_msi_bgolor', '#ff6f6f'); ?>>
                        <w:anchorlock/>
                        <center <?php echo $var->getHtmlAttribute('style', 'review_grid_button_textstyle', "color:#ffffff; font-family:'Cabin', Helvetica, Arial, sans-serif;font-size:14px;font-weight:regular;"); ?> ><?php echo $var->getValue('review_grid_button_text', "Write a Review", false);?></center>
                        </v:roundrect>
                        <![endif]-->
                        <div style="mso-hide:all;">
                            <a class="mteditor-bgcolor button-width" data-disable-href="1"
                                href="<?php echo $block->getReviewLink($block->getItem()); ?>"
                                <?php echo $var->getHtmlAttribute('bgcolor', 'review_grid_button_msi_bgolor', '#ff6f6f'); ?>
                                <?php echo $var->getHtmlAttribute('style', 'review_grid_button', 'background-color:#ff6f6f;border-radius:5px;color:#ffffff;display:inline-block;line-height:45px;text-align:center;text-decoration:none;-webkit-text-size-adjust:none;'); ?>
                                class="mteditor-bgcolor button-width" data-disable-href="1">
                                <span
                                    <?php echo $var->getTextEditAttribute('review_grid_button_text');?>
                                    <?php echo $var->getHtmlAttribute('style', 'review_grid_button_text_style', "color:#ffffff; font-family:'Cabin', Helvetica, Arial, sans-serif;font-size:14px;font-weight:regular;"); ?>
                                    class="mteditor-color button-text-color">
                                        <?php echo $var->getValue('review_grid_button_text', "Write a Review", false);?>
                                 </span>
                            </a>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>