<script>
    var feedId = getUrlParam('ff'),
        product = getUrlParam('fp'),
        currentDate = new Date(),
        session = getCookie('feed_session');

    if (!session) {
        session = '' + Math.floor(currentDate.getTime() / 1000) + Math.floor(Math.random() * 10000001);
    }

    if (session && feedId > 0 && product > 0) {
        setCookie('feed_session', session, {expires: 365, path: '/'});
        setCookie('feed_id', feedId, 365);

        var xhr = new XMLHttpRequest(),
            baseUrl = '<?php echo $block->escapeUrl($block->getBaseUrl()) ?>',
            url = BASE_URL + '?rnd=' + Math.floor(Math.random() * 10000001) + "&feed=" + feedId + "&session=" + session + "&product=" + product;

        xhr.open('GET', url, true);
        xhr.setRequestHeader('Content-Type', 'application/json');
        xhr.send();
    }

    function getUrlParam(name) {
        let results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);

        if (results === null) {
            return '';
        } else {
            return results[1] || 0;
        }
    }

    function getCookie(cookieName) {
        var name = cookieName + "=",
            decodedCookie = decodeURIComponent(document.cookie),
            cookieArray = decodedCookie.split(';');

        for (var i = 0; i < cookieArray.length; i++) {
            var cookie = cookieArray[i].trim();
            if (cookie.indexOf(name) === 0) {
                return cookie.substring(name.length, cookie.length);
            }
        }

        return null;
    }

    function setCookie(cookieName, cookieValue, expirationDays) {
        var d = new Date();
        d.setTime(d.getTime() + (expirationDays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toUTCString();
        document.cookie = cookieName + "=" + cookieValue + ";" + expires + ";path=/";
    }
</script>
