<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>We will be back soon</title>
    <meta http-equiv="refresh" content="120"/>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content=""/>
    <meta name="robots" content="*"/>
    <meta name="robots" content="noindex, nofollow"/>
    <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0"/>
    <link rel="stylesheet" href="https://poshace.com/pub/errors/creatuity_maintenance/maintenance_creatuity_default/css/styles.css" type="text/css"/>
    <link rel="stylesheet" href="https://poshace.com/pub/errors/creatuity_maintenance/maintenance_creatuity_default/css/font-awesome.min.css"/>
    <link rel="icon" href="https://poshace.com/pub/errors/creatuity_maintenance/maintenance_creatuity_default/images/favicon.png" type="image/x-icon"/>
    <link rel="shortcut icon" href="https://poshace.com/pub/errors/creatuity_maintenance/maintenance_creatuity_default/images/favicon.png" type="image/x-icon"/>
    <script src="https://poshace.com/pub/errors/creatuity_maintenance/maintenance_creatuity_default/js/countdown.js"></script>
</head>
<body >
<div class="wrapper">
    <div class="page">
        <div class="main-container" style="background: #fff;">
            <div class="main col1-layout" style="background:#FFFFFE">
                <div id="main" class="col-main">
                    <div class="logo-container">
                                            </div>
                                            <div class="page-title ">
                            <h1 style="color:#000000">We will be back soon</h1>
                        </div>
                                                                <p style="color:#000000">The server is temporarily unable to service your request due to maintenance downtime or capacity problems. We will be back soon.</p>
                                        <div class="counter">
                        <script src="https://poshace.com/?creatuity_maintenance_countdown_data=1"
                                type="text/javascript"></script>
                    </div>
                                                        </div>
            </div>
        </div>
        <div class="footer-container">
            <div class="footer">
                                    <address
                            class="copyright" >Copyright © 2017 Magento. All rights reserved.</address>
                            </div>
        </div>
    </div>
</div>

</body>
</html>
