<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table"
           summary="<?= $escaper->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $escaper->escapeHtml(__('Items Ordered')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()): ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-top"
                        class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <tr>
                <th class="col name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                <th class="col subtotal"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
            </tr>
        </thead>
        <?php $items = $block->getItems(); ?>
        <?php $giftMessage = ''?>
        <?php foreach ($items as $item):
            if ($item->getParentItem()):
                continue;
            endif;
            ?>
            <tbody>
                <?= $block->getItemHtml($item) ?>
                <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)
                        ->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()): ?>
                    <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
                        ->getGiftMessageForEntity($item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                               id="order-item-gift-message-link-<?= (int) $item->getId() ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                               data-item-id="<?= (int) $item->getId() ?>">
                                <?= $escaper->escapeHtml(__('Gift Message')) ?>
                            </a>
                            <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)
                                ->getGiftMessageForEntity($item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?= (int) $item
                                ->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?= $escaper->escapeHtml(__('Close')) ?>"
                                   aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                                   data-item-id="<?= (int) $item->getId() ?>"
                                   class="action close">
                                    <?= $escaper->escapeHtml(__('Close')) ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label">
                                            <?= $escaper->escapeHtml(__('From')) ?></strong>
                                        <?= $escaper->escapeHtml($giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label">
                                            <?= $escaper->escapeHtml(__('To')) ?></strong>
                                        <?= $escaper->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message">
                                        <?= /* @noEscape */ $this->helper(\Magento\GiftMessage\Helper\Message::class)
                                            ->getEscapedGiftMessage($item) ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php if ($block->isPagerDisplayed()): ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-bottom"
                        class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <?= $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
</div>
<?php if ($giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>



<?php
$order = $block->getOrder(); // Get the order object
$helper = $this->helper(\Vdcstore\CustomCheckoutFields\Helper\Data::class);
$values1 = $helper->getCustomFieldValue('title_field_1');
$showCustomField1 = $helper->isCustomFieldVisible1();
$customFieldValue = $order ? $order->getCustomField() : '';
?>

<?php if ($order && $showCustomField1 && !empty($customFieldValue)) : ?>
    <section class="admin__page-section order-additional-information">
        <div class="admin__page-section-title">
            <strong class="title"><?= $escaper->escapeHtml(__('Buyer Order Information')) ?></strong>
        </div>

        <div class="admin__page-section-content order-additional-information-container">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th><?= $escaper->escapeHtml($values1) ?></th>
                            <td><?= $escaper->escapeHtml($customFieldValue) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>



