<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$buttonTitle = $this->stripTags(__('Buy Now'));
$_product = $block->getProduct();
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
?>
<?php if ($helper->getConfig('pages/product_view/display_buy_now_button')) : ?>
<div class="action primary buy-now">
<button type="submit"
        data-mage-init='{"themewidgets": {"codazon.buyNow": {}}}'
        data-action="buynow"
        title="<?php echo $buttonTitle ?>"
        class="action primary buy-now new-inner-button"
        id="product-buy-now-button">
    <span><?php echo $buttonTitle ?></span>
</button>
</div>
<?php endif ?>

<style>
@media only screen and (min-width: 768px) {
    .product-view-style-04 .product-info-main .box-tocart .actions>button, .product-view-style-04 .product-info-main .box-tocart .actions>a {
        min-width: calc((100% - 120px) / 2);
    }
}
</style>
<?php if($_product->getBuyFromAmazonIn()!=""){ ?>
<!--a href="<?php echo $_product->getBuyFromAmazonIn()?>" targe="_blank"
        title="Buy From Amazon" style="margin-right:20px"
        class="action primary buy-now button"
        id="product-buy-now-buttonx">Buy From Amazon
</a-->
<a class="buy_from_amazon_button" href="<?php echo $_product->getBuyFromAmazonIn()?>">BUY FROM AMAZON</a>
<style>


@media only screen and (max-width: 767px) {
.product-view-style-04 .product-info-main .box-tocart .actions>* {
    order: 1 !important;
    width: 100%;
}
}
</style>
<?php }?>
