<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<?php
/**
 * @var \Magetrend\Affiliate\Block\Account\Info $block
 */
?>
<div class="block block-referral-form">
    <div class="block-title"><strong><?php echo $block->escapeHtml(__('Account info')) ?></strong></div>
    <div class="block-content">
        <div class="box box-affiliate-4">
            <strong class="box-title"><span>Balance</span></strong>
            <div class="box-content">
                <?php echo $block->getAccount()->getFormattedBalance(); ?>
            </div>
        </div>

        <div class="box box-affiliate-4">
            <strong class="box-title"><span>Reserved</span></strong>
            <div class="box-content">
                <?php echo $block->getAccount()->getFormattedReservedBalance(); ?>
            </div>
        </div>

        <div class="box box-affiliate-4">
            <strong class="box-title"><span>Available</span></strong>
            <div class="box-content">
                <?php echo $block->getAccount()->getFormattedAvailableBalance(); ?>
            </div>
        </div>
    </div>
</div>
