<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $block->getOrder() ?>
<div class="actions-toolbar">
    <a href="<?= $escaper->escapeUrl($block->getPrintAllCreditmemosUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $escaper->escapeHtml(__('Print All Refunds')) ?></span>
    </a>
</div>
<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo): ?>
    <div class="order-title">
        <strong><?= $escaper->escapeHtml(__('Refund #')) ?>
            <?= $escaper->escapeHtml($_creditmemo->getIncrementId()) ?> </strong>
        <a href="<?= $escaper->escapeUrl($block->getPrintCreditmemoUrl($_creditmemo)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $escaper->escapeHtml(__('Print Refund')) ?></span>
        </a>
    </div>

    <div class="table-wrapper order-items-creditmemo">
        <table class="data table table-order-items creditmemo" id="my-refund-table-<?= (int) $_creditmemo->getId() ?>">
            <caption class="table-caption"><?= $escaper->escapeHtml(__('Items Refunded')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $escaper->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $escaper->escapeHtml(__('SKU')) ?></th>
                    <th class="col price"><?= $escaper->escapeHtml(__('Price')) ?></th>
                    <th class="col qty"><?= $escaper->escapeHtml(__('Qty')) ?></th>
                    <th class="col subtotal"><?= $escaper->escapeHtml(__('Subtotal')) ?></th>
                    <th class="col discount"><?= $escaper->escapeHtml(__('Discount Amount')) ?></th>
                    <th class="col total"><?= $escaper->escapeHtml(__('Row Total')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_creditmemo->getAllItems(); ?>
            <?php foreach ($_items as $_item): ?>
                <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
            <tfoot>
                <?= $block->getTotalsHtml($_creditmemo) ?>
            </tfoot>
        </table>
    </div>
    <?= $block->getCommentsHtml($_creditmemo) ?>
<?php endforeach; ?>


<?php
$order = $block->getOrder(); // Get the order object
$helper = $this->helper(\Vdcstore\CustomCheckoutFields\Helper\Data::class);
$values1 = $helper->getCustomFieldValue('title_field_1');
$showCustomField1 = $helper->isCustomFieldVisible1();
$customFieldValue = $order ? $order->getCustomField() : '';
?>

<?php if ($order && $showCustomField1 && !empty($customFieldValue)) : ?>
    <section class="admin__page-section order-additional-information">
        <div class="admin__page-section-title">
            <strong class="title"><?= $escaper->escapeHtml(__('Buyer Order Information')) ?></strong>
        </div>

        <div class="admin__page-section-content order-additional-information-container">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tr>
                            <th><?= $escaper->escapeHtml($values1) ?></th>
                            <td><?= $escaper->escapeHtml($customFieldValue) ?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
