<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<div class="field<?php echo $block->getIsRequire()?' required':'';?>">
    <label for="mtaf_field_<?php echo (int)$block->getName();?>" class="label">
        <span><?php echo $block->getLabel(); ?></span>
    </label>
    <div class="control">
        <textarea
            <?php if ($block->getIsRequire()) : ?>
                data-validate="{required:true}"
            <?php endif; ?>
            name="<?php echo $block->escapeHtml($block->getName());?>"
            data-field-name="<?php echo $block->escapeHtml($block->getLabel())?>"
            class="<?php echo $block->getClass();?>"
            id="mtaf_field_<?php echo $block->getName();?>"></textarea>
    </div>
</div>

