<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<div class="field<?php echo $block->getIsRequire()?' required':'';?>">
    <input name="<?php echo $block->escapeHtml($block->getName());?>"
           type="checkbox"
            <?php if ($block->getIsRequire()) : ?>
               data-validate="{required:true}"
            <?php endif; ?>
           data-field-name="<?php echo $block->escapeHtml($block->getLabel())?>"
           value="1"
           class="<?php echo $block->getClass();?>"
           id="mtaf_field_<?php echo $block->getName();?>"/>
    <label for="esns_additional_<?php echo $block->escapeHtml($block->getName());?>">
        <?php echo $block->getFrontendLabel(); ?>
    </label>
</div>