<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * PHP version 5.3 or later
 *
 * @category MageTrend
 * @package  Magetend/AbandonedCart
 * @author   Edvinas Stulpinas <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     https://www.magetrend.com/magento-2-abandoned-cart
 */
// @codingStandardsIgnoreFile
?>
<?php
$item = $block->getItem();
$product = $item->getProduct();
$var = $block->getVarModel();
$helper = $block->getHelper();
?>
<?php // echo $item->getQty(); ?> <?php //echo /* @escapeNotVerified */  $block->getPrice($item); ?>
<?php /* @escapeNotVerified */// echo $block->getItemImage($item); ?>
<?php /* @escapeNotVerified */ //echo $product->getName(); ?>

<tr
    <?php echo $var->getHtmlAttribute('style', 'quote_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'quote_item_row_bgcolor', '#ffffff'); ?>
        class="mteditor-bgcolor row-bg-color">
    <td colspan="6" height="5"></td>
</tr>
<tr
    <?php echo $var->getHtmlAttribute('style', 'quote_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'quote_item_row_bgcolor', '#ffffff'); ?>
        class="mteditor-bgcolor row-bg-color">

    <td></td>
    <td align="<?php echo $block->isRTL()?'right':'left';?>" height="35">
        <?php if ($block->showImage()): ?>
        <table width="100%" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <td class="mobile-hide" width="60" valign="top"><img alt="pic" src="<?php echo $this->getItemImage($item);?>" width="60"/> </td>
                <td width="5"></td>
                <td>
                    <?php endif; ?>
                    <table cellpadding="0" cellspacing="0" border="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; ">
                        <tr>
                            <td
                                <?php echo $var->getHtmlAttribute('style', 'quote_item_name_text', 'color: #707582; font-size: 14px; height:25px!important'); ?>
                                    height="25" colspan="2" class="mteditor-color table-row-color">
                                <b><?php echo $block->escapeHtml($item->getName()) ?></b>
                            </td>
                        </tr>
                        <tr>
                            <td height="5"></td>
                        </tr>
                    </table>
                    <table cellpadding="0" width="auto" cellspacing="0" border="0" style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; ">
                        <?php if (!$helper->hideSku($item->getStoreId())) :?>
                            <tr
                                <?php echo $var->getHtmlAttribute('style', 'quote_item_options', 'color: #707582; font-size: 14px; line-height: 20px'); ?>
                                    class="mteditor-color product-options-row">
                                <td height="25" <?php echo $var->getTextEditAttribute('quote_item_options_sku_text_1');?>>
                                    <?php echo $var->getValue('quote_item_options_sku_text_1', __("Sku"));?></td>
                                <td><?php echo $block->escapeHtml($block->getSku($item)) ?></td>
                            </tr>
                        <?php endif; ?>

                        <?php if ($block->getItemOptions()): ?>
                            <?php foreach ($block->getItemOptions() as $option): ?>
                                <tr
                                    <?php echo $var->getHtmlAttribute('style', 'quote_item_options', 'color: #707582; font-size: 14px; line-height: 20px'); ?>
                                        class="mteditor-color product-options-row">

                                    <?php if (isset($option['bundle_option'])) : ?>
                                        <td height="25" colspan="2"><?php echo $option['label'] ?>&nbsp;<?php echo nl2br($option['value']) ?></td>
                                    <?php else : ?>
                                        <td height="25" colspan="2"><b><?php echo $option['label'] ?></b>&nbsp;&nbsp;<?php echo nl2br($option['value']) ?></td>
                                    <?php endif; ?>
                                </tr>
                            <?php endforeach; ?>
                            <tr>
                                <td colspan="2" height="3"></td>
                            </tr>
                        <?php endif; ?>

                    </table>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock) :?>
                        <?php echo $addInfoBlock->setItem($item)->toHtml(); ?>
                    <?php endif; ?>

                    <?php if ($block->showImage()): ?>
                </td>
            </tr>
        </table>
    <?php endif; ?>
    </td>

    <td valign="top"
        <?php echo $var->getHtmlAttribute('style', 'quote_item_name_text_qty', 'color: #707582; font-size: 14px; height:25px!important'); ?>
        class="mteditor-color table-row-color"
        align="center" height="35" >
        <?php if ($item->getQty() == 0 && $item->hasData('qty_ordered')) :?>
            <?php echo $item->getQtyOrdered()*1 ?>
        <?php else: ?>
            <?php echo (int)$item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    
    <td
            valign="top"
        <?php echo $var->getHtmlAttribute('style', 'quote_item_name_text_subtotal', 'color: #707582; font-size: 14px; height:25px!important'); ?>
            class="mteditor-color table-row-color"
            align="<?php echo $block->isRTL()?'left':'right';?>" height="35" >
        <?php echo /* @escapeNotVerified */  $block->getPrice($item); ?>

        <?php if ($block->showFPT()) : ?>
            <br/>
            <span class="mteditor-color product-fpt-price" <?php echo $var->getHtmlAttribute('style', 'quote_item_fpt_price', 'color: #707582; font-size: 14px; line-height: 20px'); ?>
            ><?php echo $block->getFormattedWeeeTax() ?></span>
        <?php endif; ?>

    </td>
   
    <td></td>

</tr>

<tr
    <?php echo $var->getHtmlAttribute('style', 'quote_item_row_style', 'background-color: #ffffff;'); ?>
    <?php echo $var->getHtmlAttribute('bgcolor', 'quote_item_row_bgcolor', '#ffffff'); ?>
        class="mteditor-bgcolor row-bg-color">
    <td colspan="6" height="5"></td>
</tr>