<?php
/**
 * Copyright © 2016 MB Vienas bitas. All rights reserved.
 * @website    www.magetrend.com
 * @package    MT Email for M2
 * @author     Edvinas Stulpinas <edwin@magetrend.com>
 */

//@codingStandardsIgnoreFile
?>
<?php $var = $block->getVarModel();?>

    <table align="center" cellpadding="0" cellspacing="0" class="container-for-gmail-android" width="100%">
        <tr
            <?php echo $var->getHtmlAttribute('style', 'secondary-bg-color-related-product', 'background-color: #ffffff;  border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5;'); ?>
            <?php echo $var->getHtmlAttribute('bgcolor', 'secondary-bg-color-color-related-product', '#ffffff'); ?> class="mteditor-bgcolor light-block">
            <td align="center" valign="top" width="100%" class="content-padding">
                <center>
                    <table cellpadding="0" cellspacing="0" width="600" class="w320">
                        <tr>
                            <td class="content-padding">
                                <table cellpadding="0" cellspacing="0" width="100%">
                                    <td <?php echo $var->getTextEditAttribute('product_list_title_text');?>
                                        <?php echo $var->getHtmlAttribute('style', 'product_list_title', ''); ?>
                                            class="mteditor-color header-md">
                                        <?php echo $var->getValue('product_list_title_text', "Block Title", false);?>
                                    </td>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding-bottom: 75px;">
                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate !important;">
                                        <tr>
                                            <td class="info-block" align="center">


                                                <table cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate !important;">
                                                    <tr>
                                                        <td>
                                                            <table cellpadding="0" cellspacing="0" width="100%">
                                                                <tr>
                                                                    <td class="info-img">
                                                                        <a href="<?php echo $block->getProductUrl(); ?>">
                                                                            <img class="info-img" src="<?php echo $block->getProductImage(); ?>" alt="img" />
                                                                        </a>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td style="padding: 15px;">
                                                                        <table cellspacing="0" cellpadding="0" width="100%">
                                                                            <tr>
                                                                                <td style="text-align:center; width:155px">
                                                                                    <a href="<?php echo $block->getProductUrl(); ?>"><span class="header-sm"><?php /* @escapeNotVerified */ echo $block->getProductName(); ?></span></a><br />
                                                                                </td>

                                                                            </tr>
                                                                            <tr>
                                                                                <td style="text-align:center; vertical-align: top;">
                                                                                    <strong>
                                                                                        <?php echo $block->getProductPrice(); ?>
                                                                                    </strong>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                                <tr>
                                                                    <td style="padding: 15px;">
                                                                        <!--[if mso]>
                                                                        <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="<?php echo $block->getProductUrl(); ?>" style="height:45px;v-text-anchor:middle;width:155px;" arcsize="15%" strokecolor="#ffffff" <?php echo $var->getHtmlAttribute('fillcolor', 'product_grid_button_msi_bgolor', '#ff6f6f'); ?>>
                                                                        <w:anchorlock/>
                                                                        <center <?php echo $var->getHtmlAttribute('style', 'product_grid_text_style', "color:#ffffff; font-family:'Cabin', Helvetica, Arial, sans-serif;font-size:14px;font-weight:regular;"); ?> ><?php echo $var->getValue('product_grid_text', "View Now!", false);?></center>
                                                                        </v:roundrect>
                                                                        <![endif]-->
                                                                        <div style="mso-hide:all;">
                                                                            <a class="mteditor-bgcolor button-width" data-disable-href="1"
                                                                               href="<?php echo $block->getProductUrl(); ?>"
                                                                                <?php echo $var->getHtmlAttribute('bgcolor', 'product_grid_button_msi_bgolor', '#ff6f6f'); ?>
                                                                                <?php echo $var->getHtmlAttribute('style', 'product_grid_button', 'background-color:#ff6f6f;border-radius:5px;color:#ffffff;display:inline-block;line-height:45px;text-align:center;text-decoration:none;-webkit-text-size-adjust:none;'); ?>
                                                                               class="mteditor-bgcolor button-width" data-disable-href="1">
                                <span
                                    <?php echo $var->getTextEditAttribute('product_grid_text');?>
                                    <?php echo $var->getHtmlAttribute('style', 'product_grid_text_style', "color:#ffffff; font-family:'Cabin', Helvetica, Arial, sans-serif;font-size:14px;font-weight:regular;"); ?>
                                        class="mteditor-color button-text-color">
                                        <?php echo $var->getValue('product_grid_text', "View Now!", false);?>
                                 </span>
                                                                            </a>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>

                                            </td>
                                        </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                </center>
            </td>
        </tr>
    </table>
