<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Options\Type\Hidden */ ?>
<script id="custom-option-hidden-type-template" type="hidden/x-magento-template">
    <div style="display: none!important;"
         id="field_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset">
    </div>
</script>
