<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<div id="modal-container">
    <div data-role="spinner" class="admin__data-grid-loading-mask">
        <div class="spinner">
            <span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span>
        </div>
    </div>
    <div id="modal-context">
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "entityEditForm": <?php echo $block->getJsonConfig(); ?>
        }
    }
</script>