<?php
/**
 * MB "Vienas bitas" (Magetrend.com)
 *
 * @category MageTrend
 * @package  Magetend/Affiliate
 * @author   Edvinas St. <edwin@magetrend.com>
 * @license  http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link     http://www.magetrend.com/magento-2-affiliate
 */
?>
<?php if ($block->isActive()) : ?>
<script type="text/x-magento-init">
    {
        "*": {
            "mtafReferral": <?php echo $block->getJsonConfig(); ?>
        }
    }
</script>
<?php endif; ?>